"""empty message

Revision ID: 2f8ab07c026
Revises: 3f01ccd0383
Create Date: 2015-10-02 20:55:01.479756

"""

# revision identifiers, used by Alembic.
revision = '2f8ab07c026'
down_revision = '3f01ccd0383'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('language_name', sa.String(length=100), nullable=False),
    sa.Column('dir', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code'),
    sa.UniqueConstraint('language_name')
    )
    op.create_foreign_key(None, 'translator_languages', 'languages', ['language_code'], ['language_code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translator_languages', type_='foreignkey')
    op.drop_table('languages')
    ### end Alembic commands ###
