"""empty message

Revision ID: df4504c743
Revises: e1210a6849
Create Date: 2015-10-02 20:43:05.592320

"""

# revision identifiers, used by Alembic.
revision = 'df4504c743'
down_revision = 'e1210a6849'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
