"""empty message

Revision ID: e1210a6849
Revises: 49629086176
Create Date: 2015-10-02 20:38:59.418840

"""

# revision identifiers, used by Alembic.
revision = 'e1210a6849'
down_revision = '49629086176'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
